version: '3.8'

services:
  main_app:
    build:
      context: .
      dockerfile: main_app/Dockerfile.main_app
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  ping_app:
    build:
      context: .
      dockerfile: ping_app/Dockerfile.ping_app
    depends_on:
      - main_app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
